### ISSUE TITLE
Nome do bot não é apresentado corretamente no primeiro uso

### ISSUE THREAD

**Issue by AlexandreSNeto** [hubot-js/hubot.js#59]
Configurei meu bot com um nome personalizado e ao executar o bot pela primeira vez, no texto de apresentação a primeira mensagem está mostrando o bot com o nome 'hubot' e não com o nome personalizado que eu configurei.

Segue texto apresentado no slack:
`Hello, @Alexandre Silveira Neto ! My name is hubot and from now on I will help you with some tasks using the Slack.`

Aparentemente o nome "hubot" está **fixo** no arquivo `first-run.js` na function `message1`:
```
function message1(hubot, core, message) {
  return hubot.speech().hello(core.getUserById(message.user)).append('firstUse.message1', { botName: 'hubot' }).end();
}
```

**Comment by robsonbittencourt** [comment]
Fixed. Thanks.
